apiVersion: v1
kind: Service
metadata:
  name: grafanademoservice
  labels:
    run: grafanademoservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    run: grafanademoapp
